Repository david-fisher/320-F20-Track-IV, pull requests merged in 2020-11, with the labels that each got.

#69 Move stubs on `server/index.js` to proper routers and do other several changes
  .env
  .gitignore
  package-lock.json
  package.json
  server/auth.js
  server/db/index.js
  server/index.js
  server/route/dashboard.js
  server/route/simulation.js
Labels: development

#71 Create tests for DB access methods which gets simulations using mocha
  package-lock.json
  package.json
  server/db/index.js
  server/test/db.spec.js
Labels: db, help wanted, question, testing

#89 Create DB access points for all tables
  backend/server/db/conversation_task.js
  backend/server/db/courses.js
  backend/server/db/enrolled.js
  backend/server/db/index.js
  backend/server/db/instructs.js
  backend/server/db/issues.js
  backend/server/db/mcq.js
  backend/server/db/mcq_option.js
  backend/server/db/mcq_response.js
  backend/server/db/pages.js
  backend/server/db/partof.js
  backend/server/db/pool.js
  backend/server/db/prompt.js
  backend/server/db/prompt_response.js
  backend/server/db/question.js
  backend/server/db/response.js
  backend/server/db/scenario.js
  backend/server/db/score.js
  backend/server/db/stakeholder_choices.js
  backend/server/db/stakeholders.js
  backend/server/db/submissions.js
  backend/server/db/users.js
  backend/server/models/index.js
  backend/server/models/pool.js
  backend/server/route/simulation.js
  database/database_setup.sql
  server/route/auth.js
Labels: db, development, enhancement

#96 Add stubs of unit tests for DB access points
  backend/server/db/conversation_task.js
  backend/server/db/courses.js
  backend/server/db/enrolled.js
  backend/server/db/instructs.js
  backend/server/db/mcq.js
  backend/server/db/mcq_option.js
  backend/server/db/mcq_response.js
  backend/server/db/pages.js
  backend/server/db/partof.js
  backend/server/db/prompt.js
  backend/server/db/prompt_response.js
  backend/server/db/question.js
  backend/server/db/response.js
  backend/server/db/scenario.js
  backend/server/db/score.js
  backend/server/db/stakeholder_choices.js
  backend/server/db/stakeholders.js
  backend/server/db/submissions.js
  backend/server/test/db.spec.js
  backend/server/test/db/conversation_task.spec.js
  backend/server/test/db/courses.spec.js
  backend/server/test/db/enrolled.spec.js
  backend/server/test/db/instructs.spec.js
  backend/server/test/db/issues.spec.js
  backend/server/test/db/mcq.spec.js
  backend/server/test/db/mcq_option.spec.js
  backend/server/test/db/mcq_response.spec.js
  backend/server/test/db/pages.spec.js
  backend/server/test/db/partof.spec.js
  backend/server/test/db/prompt.spec.js
  backend/server/test/db/prompt_response.spec.js
  backend/server/test/db/question.spec.js
  backend/server/test/db/response.spec.js
  backend/server/test/db/scenario.spec.js
  backend/server/test/db/score.spec.js
  backend/server/test/db/stakeholder_choices.spec.js
  backend/server/test/db/stakeholders.spec.js
  backend/server/test/db/submissions.spec.js
  backend/server/test/db/users.spec.js
Labels: db, testing

#115 Implement Conclusions page
  scenario_editor/src/App.js
  scenario_editor/src/Pages/Editor/Conclusions.js
Labels: development

#123 Add and refactor Reflection Pages
  scenario_editor/src/App.js
  scenario_editor/src/Pages/Dashboard.js
  scenario_editor/src/Pages/Editor/FinalReflection.js
  scenario_editor/src/Pages/Editor/Introduction.js
  scenario_editor/src/Pages/Editor/MiddleReflection.js
  scenario_editor/src/Pages/Editor/PlayerResponses.js
  scenario_editor/src/Pages/Editor/Reflections.js
  scenario_editor/src/components/Nav.js
Labels: development

#124 Created Consequences page, Updated styling, and updated intro hub
  scenario_editor/src/App.js
  scenario_editor/src/Pages/Editor/Consequences.js
  scenario_editor/src/Pages/Editor/FinalReflection.js
  scenario_editor/src/Pages/Editor/IntroductionHub.js
  scenario_editor/src/Pages/Editor/Reflections.js
  scenario_editor/src/Pages/Editor/UserAgreement.js
  scenario_editor/src/components/Nav.js
Labels: development
