Repository david-fisher/320-F20-Track-IV, pull requests merged in 2020-10, with the labels that each got.

#32 Implement login demo
  package-lock.json
  package.json
  server/auth.js
  server/db/users.js
  server/index.js
  server/route/auth.js
  server/route/index.js
Labels: auth, development, enhancement

#49 Add stubs for dashboard and for adding/updating simulation
  server/route/dashboard.js
  server/route/index.js
  server/route/simulation.js
Labels: development, enhancement

#56 Update Login Pages, page routing, and component css files. Remove un-needed files.
  scenario_editor/package-lock.json
  scenario_editor/package.json
  scenario_editor/src/App.js
  scenario_editor/src/Home/Home.css
  scenario_editor/src/Introduction/Introduction.js
  scenario_editor/src/Login/Login.js
  scenario_editor/src/NewScenario/new_scenario.css
  scenario_editor/src/NewScenario/new_scenario.js
  scenario_editor/src/Welcome/Welcome.css
  scenario_editor/src/Welcome/Welcome.js
  scenario_editor/src/components/Login.css
  scenario_editor/src/components/Login.js
  scenario_editor/src/components/Welcome.css
  scenario_editor/src/components/Welcome.js
Labels: enhancement
